# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.12.2/ibek.ioc.schema.json

# TODO replace above with the generic IOC schema this IOC is based on
ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: An IOC instance that simulates a detector

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: GMT0BST

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: ADSimDetector.simDetector
    PORT: DET.DET
    P: BL01T-EA-CAM-01
    R: ":DET:"
    DATATYPE: 0
    WIDTH: 1024
    HEIGHT: 1024

  - type: epics.PostStartupCommand
    command: |
      dbpf BL01T-EA-CAM-01:DET:AcquireTime 0.1
      dbpf BL01T-EA-CAM-01:ARR:EnableCallbacks 1
      dbpf BL01T-EA-CAM-01:DET:Acquire 1

  - type: ADCore.NDStdArrays
    PORT: DET.ARR
    P: BL01T-EA-CAM-01
    R: ":ARR:"
    NDARRAY_PORT: DET.DET
    TYPE: Int8
    FTVL: CHAR
    NELEMENTS: 1048576
